### ISSUE TITLE
integer-simple no longer exists (default not specified)

### ISSUE THREAD

**Issue by mrd** [bos/text#138]
Hi,

Two issues in text.cabal, really, with a simple fix. One: integer-simple seems to be called integer-pure nowadays.

Two: the Cabal manual says that the "default Default" for a flag is True. This means that "integer-simple" is being enabled by default. At least, this seems to happen on newer GHC versions. My older install defaults to False for that flag so I didn't notice this problem until today. Text is not installable from hackage using cabal-install on my GHC 7.10 setup, as a result, with defaults.

Suggested fix: change name to "integer-pure" and add a line that says "default: False".

The commit named 35b1a2059476a09523c29c830ca7c223f1de8c2c is related to this problem, because it removed the "default: False" line.

**Comment by bos** [comment]
I believe this should be fixed now.

**Comment by hvr** [comment]
@bos I'm utterly surprised and confused about this bug-report on two counts:

 1. GHC still only has support for `integer-gmp` (default configuration) or `integer-simple` as build-time configuration. I don't know where this rumour about `integer-pure` having replaced `integer-simple` came from.
 2. While it is true that the `integer-simple` flag in `text-1.2.1.3` was on by default, it was an automatic flag. So `cabal` would have happily toggled it. I'm surprised `cabal install text` failed to toggle that flag for @mrd, as this would point to a serious bug in `cabal` which would have caused problems for a lot of other users.

**Comment by bos** [comment]
Hmm, fair enough. What do you suggest we do, then?

**Comment by hvr** [comment]
I'd suggest we revert the renaming back to `integer-simple`, and make the flag automatic again (albeit with a `default: false` to be on the safe side -- after all, 99% of users need the `false`-default, so we want the cabal solver to start with that default).

I can probably test the integer-simple configuration of `text` in a couple of days, as I need to make sure GHC 8.0RC1 still works with integer-simple (I last tested it 2 months ago) anyway...

**Comment by quyse** [comment]
I find this change quite disruptive. Actually I've never heard about `integer-pure` before the moment, and I don't see any information about using this library as an integer-simple replacement. I guess such a move would involve at least rebuilding ghc with integer-pure instead of integer-simple, which is not the easiest thing to do; also other libraries (e.g. `scientific`) do depend on integer-simple, so unless we change them too, we cannot use them together.
So, I fully agree with @hvr, this change should be reverted, and just the correct default value (`false`) for the `integer-simple` flag should be added. It's interesting though, why the problem with default value wasn't noticed before. For `stack` users my only guess is that the `integer-simple` flag is set to fixed value coming from stackage snapshot; however if you add `text` to `extra-deps` in stack.yaml, `integer-simple` is set to true by automatic logic, and it fails to build.

**Comment by mitchty** [comment]
I'm not sure a false default is correct, when cross compiling ghc using integer-simple is pretty common to keep the cross compilation simple. This change means the following occurs when trying to bootstrap cabal via a ghc compiled just with integer-simple:
```
[1 of 1] Compiling Main             ( Setup.lhs, Setup.o )
Linking Setup ...
Configuring text-1.2.2.0...
Setup: At least the following dependencies are missing:
integer-gmp >=0.2

Error during cabal-install bootstrap:
Configuring the text package failed.
>>> ERROR: ghc: all failed
>>> ghc: Uninstalling dependencies...
```

I think it should be the opposite, detect if gmp is available and then turn integer-simple off. I grant cross compilation is a bit of a niche use case but arguably a rather important one to support.

**Comment by rwbarton** [comment]
As far as I can tell everything was totally fine before the change in this issue.

* Somehow @mrd had a custom GHC built against integer-pure (which is not a supported configuration) rather than integer-gmp or integer-simple, and didn't realize this was a custom configuration.

* Since both integer-gmp and integer-simple were missing, Cabal could not find a value for the flag that led to a valid install plan.

* Cabal reported an error based on the default value of the integer-simple flag, true. @mrd thought this meant that Cabal had committed to the default value, when it really tried both values.

All that really needs to be done here is reverting b806d9491c740dfcbf172d2936f1eeb3b72d3492.

The default value is only relevant for someone who has both integer-gmp and integer-simple installed (not sure whether this is even supported). But defaulting to false is probably more sensible than true, like @hvr says.
